//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGames.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoardGames.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string GameMatches_Date {
            get {
                return ResourceManager.GetString("GameMatches_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game not found.
        /// </summary>
        public static string GameMatches_GameNotFound {
            get {
                return ResourceManager.GetString("GameMatches_GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboards.
        /// </summary>
        public static string GameMatches_Leaderboards {
            get {
                return ResourceManager.GetString("GameMatches_Leaderboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string GameMatches_Matches {
            get {
                return ResourceManager.GetString("GameMatches_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found!.
        /// </summary>
        public static string GameMatches_NoMatchFound {
            get {
                return ResourceManager.GetString("GameMatches_NoMatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr..
        /// </summary>
        public static string GameMatches_Nr {
            get {
                return ResourceManager.GetString("GameMatches_Nr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no matches for.
        /// </summary>
        public static string GameMatches_ThereAreCurrentlyNoMatchesFor {
            get {
                return ResourceManager.GetString("GameMatches_ThereAreCurrentlyNoMatchesFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no matches for .
        /// </summary>
        public static string GameMatches_ThereAreCurrentlyNoMatchesFor_gameName {
            get {
                return ResourceManager.GetString("GameMatches_ThereAreCurrentlyNoMatchesFor_gameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win %.
        /// </summary>
        public static string GameMatches_Win {
            get {
                return ResourceManager.GetString("GameMatches_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        public static string GameMatches_Winner {
            get {
                return ResourceManager.GetString("GameMatches_Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string GameMatches_Wins {
            get {
                return ResourceManager.GetString("GameMatches_Wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name....
        /// </summary>
        public static string Games_SearchByName {
            get {
                return ResourceManager.GetString("Games_SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Review.
        /// </summary>
        public static string Match_AddReview {
            get {
                return ResourceManager.GetString("Match_AddReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current match?.
        /// </summary>
        public static string Match_AreYouSureYouWantToDeleteTheCurrentMatch {
            get {
                return ResourceManager.GetString("Match_AreYouSureYouWantToDeleteTheCurrentMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the review?.
        /// </summary>
        public static string Match_AreYouSureYouWantToDeleteTheReview {
            get {
                return ResourceManager.GetString("Match_AreYouSureYouWantToDeleteTheReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Match_Delete {
            get {
                return ResourceManager.GetString("Match_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete match.
        /// </summary>
        public static string Match_DeleteMatch {
            get {
                return ResourceManager.GetString("Match_DeleteMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete review.
        /// </summary>
        public static string Match_DeleteReview {
            get {
                return ResourceManager.GetString("Match_DeleteReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Match_Duration {
            get {
                return ResourceManager.GetString("Match_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Match_Location {
            get {
                return ResourceManager.GetString("Match_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Match_Player {
            get {
                return ResourceManager.GetString("Match_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Match_Points {
            get {
                return ResourceManager.GetString("Match_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Match_Reviews {
            get {
                return ResourceManager.GetString("Match_Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Match_Share {
            get {
                return ResourceManager.GetString("Match_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        public static string Match_Stars {
            get {
                return ResourceManager.GetString("Match_Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration in min.
        /// </summary>
        public static string NewMatch_DurationInMin {
            get {
                return ResourceManager.GetString("NewMatch_DurationInMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string NewMatch_Save {
            get {
                return ResourceManager.GetString("NewMatch_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a faction.
        /// </summary>
        public static string NewMatch_SelectAFaction {
            get {
                return ResourceManager.GetString("NewMatch_SelectAFaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Game.
        /// </summary>
        public static string NewMatch_SelectAGame {
            get {
                return ResourceManager.GetString("NewMatch_SelectAGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Location.
        /// </summary>
        public static string NewMatch_SelectALocation {
            get {
                return ResourceManager.GetString("NewMatch_SelectALocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select players.
        /// </summary>
        public static string NewMatch_SelectPlayers {
            get {
                return ResourceManager.GetString("NewMatch_SelectPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string Settings_DarkMode {
            get {
                return ResourceManager.GetString("Settings_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities.
        /// </summary>
        public static string Settings_Entities {
            get {
                return ResourceManager.GetString("Settings_Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factions.
        /// </summary>
        public static string Settings_Factions {
            get {
                return ResourceManager.GetString("Settings_Factions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Settings_Games {
            get {
                return ResourceManager.GetString("Settings_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Settings_Locations {
            get {
                return ResourceManager.GetString("Settings_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string Settings_Players {
            get {
                return ResourceManager.GetString("Settings_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Settings {
            get {
                return ResourceManager.GetString("Settings_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Faction.
        /// </summary>
        public static string SettingsFactions_AddFaction {
            get {
                return ResourceManager.GetString("SettingsFactions_AddFaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected faction?.
        /// </summary>
        public static string SettingsFactions_AreYouSureYouWantToDeleteTheSelectedFaction {
            get {
                return ResourceManager.GetString("SettingsFactions_AreYouSureYouWantToDeleteTheSelectedFaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string SettingsFactions_Color {
            get {
                return ResourceManager.GetString("SettingsFactions_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Faction.
        /// </summary>
        public static string SettingsFactions_DeleteFaction {
            get {
                return ResourceManager.GetString("SettingsFactions_DeleteFaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete faction.
        /// </summary>
        public static string SettingsFactions_DeleteFactionMsg {
            get {
                return ResourceManager.GetString("SettingsFactions_DeleteFactionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Faction.
        /// </summary>
        public static string SettingsFactions_EditFaction {
            get {
                return ResourceManager.GetString("SettingsFactions_EditFaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faction.
        /// </summary>
        public static string SettingsFactions_Faction {
            get {
                return ResourceManager.GetString("SettingsFactions_Faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string SettingsFactions_Game {
            get {
                return ResourceManager.GetString("SettingsFactions_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Game.
        /// </summary>
        public static string SettingsGames_AddGame {
            get {
                return ResourceManager.GetString("SettingsGames_AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected game?.
        /// </summary>
        public static string SettingsGames_AreYouSureYouWantToDeleteTheSelectedGame {
            get {
                return ResourceManager.GetString("SettingsGames_AreYouSureYouWantToDeleteTheSelectedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Game.
        /// </summary>
        public static string SettingsGames_DeleteGame {
            get {
                return ResourceManager.GetString("SettingsGames_DeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete game.
        /// </summary>
        public static string SettingsGames_DeleteGameMsg {
            get {
                return ResourceManager.GetString("SettingsGames_DeleteGameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Game.
        /// </summary>
        public static string SettingsGames_EditGame {
            get {
                return ResourceManager.GetString("SettingsGames_EditGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SettingsGames_Name {
            get {
                return ResourceManager.GetString("SettingsGames_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Location.
        /// </summary>
        public static string SettingsLocations_AddLocation {
            get {
                return ResourceManager.GetString("SettingsLocations_AddLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected location?.
        /// </summary>
        public static string SettingsLocations_AreYouSureYouWantToDeleteTheSelectedLocation {
            get {
                return ResourceManager.GetString("SettingsLocations_AreYouSureYouWantToDeleteTheSelectedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Location.
        /// </summary>
        public static string SettingsLocations_DeleteLocation {
            get {
                return ResourceManager.GetString("SettingsLocations_DeleteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete location.
        /// </summary>
        public static string SettingsLocations_DeleteLocationMsg {
            get {
                return ResourceManager.GetString("SettingsLocations_DeleteLocationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Location.
        /// </summary>
        public static string SettingsLocations_EditLocation {
            get {
                return ResourceManager.GetString("SettingsLocations_EditLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Player.
        /// </summary>
        public static string SettingsPlayers_AddPlayer {
            get {
                return ResourceManager.GetString("SettingsPlayers_AddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected player?.
        /// </summary>
        public static string SettingsPlayers_AreYouSureYouWantToDeleteTheSelectedPlayer {
            get {
                return ResourceManager.GetString("SettingsPlayers_AreYouSureYouWantToDeleteTheSelectedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Player.
        /// </summary>
        public static string SettingsPlayers_DeletePlayer {
            get {
                return ResourceManager.GetString("SettingsPlayers_DeletePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete player.
        /// </summary>
        public static string SettingsPlayers_DeletePlayerMsg {
            get {
                return ResourceManager.GetString("SettingsPlayers_DeletePlayerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Player.
        /// </summary>
        public static string SettingsPlayers_EditPlayer {
            get {
                return ResourceManager.GetString("SettingsPlayers_EditPlayer", resourceCulture);
            }
        }
    }
}
